config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  # namespace :user do
  #   root :to => "homes#authenticate"
  # end

  get '/switch_theme', to: "homes#switch_theme"
  get '/entree_picker', to: "homes#authenticate"
  get '/picked_entree', to: "homes#authenticate"
  get '/entree_history', to: "homes#authenticate"
  get '/your_experience', to: "homes#authenticate"

  namespace :api do
    namespace :v1 do
      resources :change_themes, only: [:index, :create]
      resources :picked_entrees, only: [:index, :create, :update, :destroy]
      resources :reviews, only: [:edit, :create, :update, :destroy]
      resources :site_reviews, only: [:index, :create, :update, :destroy]
      resources :current_user_picked_entrees, only: [:index]
      resources :all_users_picked_entrees, only: [:index]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EntréePicker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <% if session['theme'] == "dark_path" %>

    <%= stylesheet_link_tag 'application_dark', media: 'all' %>
  <% else %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  <% end %>
  <%= csrf_meta_tags %>
</head>
<body class="watermark">
  <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="example-menu"></button>
    <div class="title-bar-title"></div>
  </div>
  <div class="top-bar-container sticky-container" data-sticky-container>
    <div class="sticky is-stuck is-at-top" data-sticky data-options="marginTop:0;">
      <nav class="top-bar" id="example-menu">
        <div class="top-bar-left">
          <h2><a href="/">EntréePicker</a></h2>
        </div>
        <div class="top-bar-right">
          <section class="top-bar-section">
            <ul class="right menu">
              <%- if current_user -%>
                <li><%= link_to 'Switch Theme', switch_theme_path %></li>
                <li><%= link_to 'Entrée Picker', entree_picker_path %></li>
                <li><%= link_to 'History', entree_history_path %></li>
                <li><%= link_to 'Your Experience', your_experience_path %></li>
                <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
              <%- else -%>
                <li><%= link_to 'Switch Theme', switch_theme_path %></li>
                <li><%= link_to 'Sign Up', new_user_registration_path %></li>
                <li><%= link_to 'Sign In', new_user_session_path %></li>
              <%- end -%>
            </ul>
          </section>
        </div>
      </nav>
    </div>
  </div>

  <div class="content grid-container">
    <div id="flash-messages">
      <%- flash.each do |key, value| -%>
        <div class="flash flash-<%= key %>">
          <%= value %>
        </div>
      <%- end -%>
    </div>

    <%= yield %>

    <%= javascript_include_tag 'application' %>

    <%- if Rails.env.development? || Rails.env.test? -%>
      <%= javascript_tag do %>
        window.railsEnv = '<%= Rails.env %>'
      <%- end -%>
    <%- end -%>
    <%= javascript_pack_tag 'application' %>
    <%= yield :extra_footer %>
  </div>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRrWfWSdjkChUXasx3gJIYuK7oKBkMQkg">
  </script>
</body>
</html>